version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "angular-ssr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ue3h25ilnbd9"
s3_prefix = "angular-ssr"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
