AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  angular-ssr-cms
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  
  ExpressApi:
    Type: AWS::Serverless::HttpApi

  AngularSSR:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "../dist/angular-ssr"
      Handler: lambda.handler
      Runtime: nodejs14.x
      Layers:
       - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:angularSSR:4"
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 10
      Description: Angular SSR
      Environment:
        Variables:
          DIST: './'
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExpressApi

Outputs:
  ApiUrl:
    Description: API URL
    Value: !Sub https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/